### ISSUE TITLE
Network creation error on PHP8

### ISSUE THREAD

**Issue by Rahe** [stuttter/wp-multi-network#187]
Hello,

On PHP when creating a new network I have this error :

```
[Mon Mar 21 11:44:48.416171 2022] [fcgid:warn] [pid 23966] [client 163.172.230.233:38458] mod_fcgid: stderr: PHP Fatal error:  Uncaught Error: Undefined constant "UPLOADBLOGSDIR" in /home/test.lndo.site/public_html/web/wp/wp-includes/ms-site.php:708, referer: https://test.lndo.site/wp/wp-admin/network/admin.php?page=add-new-network
[Mon Mar 21 11:44:48.416238 2022] [fcgid:warn] [pid 23966] [client 163.172.230.233:38458] mod_fcgid: stderr: Stack trace:, referer: https://test.lndo.site/wp/wp-admin/network/admin.php?page=add-new-network
[Mon Mar 21 11:44:48.416246 2022] [fcgid:warn] [pid 23966] [client 163.172.230.233:38458] mod_fcgid: stderr: #0 /home/test.lndo.site/public_html/web/wp/wp-includes/class-wp-hook.php(307): wp_initialize_site(), referer: https://test.lndo.site/wp/wp-admin/network/admin.php?page=add-new-network
[Mon Mar 21 11:44:48.416254 2022] [fcgid:warn] [pid 23966] [client 163.172.230.233:38458] mod_fcgid: stderr: #1 /home/test.lndo.site/public_html/web/wp/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(), referer: https://test.lndo.site/wp/wp-admin/network/admin.php?page=add-new-network
[Mon Mar 21 11:44:48.416261 2022] [fcgid:warn] [pid 23966] [client 163.172.230.233:38458] mod_fcgid: stderr: #2 /home/test.lndo.site/public_html/web/wp/wp-includes/plugin.php(474): WP_Hook->do_action(), referer: https://test.lndo.site/wp/wp-admin/network/admin.php?page=add-new-network
[Mon Mar 21 11:44:48.416267 2022] [fcgid:warn] [pid 23966] [client 163.172.230.233:38458] mod_fcgid: stderr: #3 /home/test.lndo.site/public_html/web/wp/wp-includes/ms-site.php(105): do_action(), referer: https://test.lndo.site/wp/wp-admin/network/admin.php?page=add-new-network
[Mon Mar 21 11:44:48.416274 2022] [fcgid:warn] [pid 23966] [client 163.172.230.233:38458] mod_fcgid: stderr: #4 /home/test.lndo.site/public_html/web/wp/wp-includes/ms-functions.php(1405): wp_insert_site(), referer: https://test.lndo.site/wp/wp-admin/network/admin.php?page=add-new-network
[Mon Mar 21 11:44:48.416281 2022] [fcgid:warn] [pid 23966] [client 163.172.230.233:38458] mod_fcgid: stderr: #5 /home/test.lndo.site/public_html/web/app/plugins/wp-multi-network/wp-multi-network/includes/functions.php(560): wpmu_create_blog(), referer: https://test.lndo.site/wp/wp-admin/network/admin.php?page=add-new-network
[Mon Mar 21 11:44:48.416288 2022] [fcgid:warn] [pid 23966] [client 163.172.230.233:38458] mod_fcgid: stderr: #6 /home/test.lndo.site/public_html/web/app/plugins/wp-multi-network/wp-multi-network/includes/classes/class-wp-ms-networks-admin.php(903): add_network(), referer: https://test.lndo.site/wp/wp-admin/network/admin.php?page=add-new-network
[Mon Mar 21 11:44:48.416306 2022] [fcgid:warn] [pid 23966] [client 163.172.230.233:38458] mod_fcgid: stderr: #7 /home/test.lndo.site/public_html/web/app/plugins/wp-multi-network/wp-multi-network/includes/classes/class-wp-ms-networks-admin.php(319): WP_MS_Networks_Admin->handle_add_network(), referer: https://test.lndo.site/wp/wp-admin/network/admin.php?page=add-new-network
[Mon Mar 21 11:44:48.416313 2022] [fcgid:warn] [pid 23966] [client 163.172.230.233:38458] mod_fcgid: stderr: #8 /home/test.lndo.site/public_html/web/wp/wp-includes/class-wp-hook.php(307): WP_MS_Networks_Admin->route_save_handlers(), referer: https://test.lndo.site/wp/wp-admin/network/admin.php?page=add-new-network
[Mon Mar 21 11:44:48.416320 2022] [fcgid:warn] [pid 23966] [client 163.172.230.233:38458] mod_fcgid: stderr: #9 /home/test.lndo.site/public_html/web/wp/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(), referer: https://test.lndo.site/wp/wp-admin/network/admin.php?page=add-new-network
[Mon Mar 21 11:44:48.416326 2022] [fcgid:warn] [pid 23966] [client 163.172.230.233:38458] mod_fcgid: stderr: #10 /home/test.lndo.site/public_html/web/wp/wp-includes/plugin.php(474): WP_Hook->do_action(), referer: https://test.lndo.site/wp/wp-admin/network/admin.php?page=add-new-network
[Mon Mar 21 11:44:48.416332 2022] [fcgid:warn] [pid 23966] [client 163.172.230.233:38458] mod_fcgid: stderr: #11 /home/test.lndo.site/public_html/web/wp/wp-admin/admin.php(175): do_action(), referer: https://test.lndo.site/wp/wp-admin/network/admin.php?page=add-new-network
[Mon Mar 21 11:44:48.416338 2022] [fcgid:warn] [pid 23966] [client 163.172.230.233:38458] mod_fcgid: stderr: #12 /home/test.lndo.site/public_html/web/wp/wp-admin/network/admin.php(13): require_once('...'), referer: https://test.lndo.site/wp/wp-admin/network/admin.php?page=add-new-network
[Mon Mar 21 11:44:48.416344 2022] [fcgid:warn] [pid 23966] [client 163.172.230.233:38458] mod_fcgid: stderr: #13 {main}, referer: https://test.lndo.site/wp/wp-admin/network/admin.php?page=add-new-network
[Mon Mar 21 11:44:48.416350 2022] [fcgid:warn] [pid 23966] [client 163.172.230.233:38458] mod_fcgid: stderr:   thrown in /home/test.lndo.site/public_html/web/wp/wp-includes/ms-site.php on line 708, referer: https://test.lndo.site/wp/wp-admin/network/admin.php?page=add-new-network
```

The constant is, indeed undefined.

Nicolas,

**Comment by JJJ** [comment]
This should be happening automatically inside of `ms_upload_constants()`.

Are you sure you are using WordPress Multisite?
